### PR TITLE
fix: improperly quoted tags values in 1password.1pif test asset

### PR DESCRIPTION
**Pull request by davidandreoletti**
**fix: improperly quoted tags values in 1password.1pif test asset #209** 

Values were single quoted instead of double quoted.

**doc: filter dependency for pip based installs**

self explanatory.

PS: Thank for conditional test runs code to reduce the noise.

### CODE REVIEW

**Comment by davidandreoletti** [comment]
@roddhjav There you go.

**Comment by davidandreoletti** [comment]
What's the most likely time window for the next release ?

**Comment by davidandreoletti** [comment]
> Next release should come soon (it is about time).

@roddhjav At this point, I need pass-import to issue a new official release with the fixes I contributed, for a production system.

Is that something that can be done within this week/next week ?

**Comment by roddhjav** [comment]
That is now done.

**Comment by davidandreoletti** [comment]
Fantastic! Thank you.

**Pull request merged**
