### PR TITLE
feat: Filter would be exported entries based on JSONPath filter expression

### PR DESCRIPTION
**Pull request by davidandreoletti**
Here is an example, for imported entries with a 'tags' field, one can only export entries with tag value containing 'Defaults'.

This filter is independent of the input file format used as it runs prior to exporting entries to the target password manager.

```
pass-import --force --verbose --filter
'$.entries[*].tags[?@="Defaults"]' csv 1password /tmp/1Password.1pif/data.1pif --out /tmp/data.csv
```

Tested on:
- 1password 1PIF format manually
- generic password manager automatically (see unit test)

Documentation:
 - `--help` documentation updated. The helper function seems not to support a long form description. The doc is added to the `help` field instead.
 - README --help updated too.

### CODE REVIEW

**Comment by roddhjav** [comment]
Thanks. Nice feature.

Can you make `jsonpath_ng` an optional requirement. As it is only supported in 1password, I don't want to require it as a strict deps.

**Comment by davidandreoletti** [comment]
It was tested on 1Password but the logic is password manager independent.

See unit test. 

Let me know if your  POV changed.

**Comment by davidandreoletti** [comment]
Got it.

**Comment by roddhjav** [comment]
Thanks. Merged

**Comment by davidandreoletti** [comment]
Will look into it today.

**Pull request merged**
