### PR TITLE
Update myki.py

### PR DESCRIPTION
**Pull request by WNemencha**
Myki is closing out, but they changed the fields name so it was not possible to import in pass... Fixed that. :)

c.f. https://myki.com/blog/important-announcement-we-got-acquired/

### CODE REVIEW

**Comment by roddhjav** [comment]
Thank for this PR. Can you also update the test csv file in `tests/assets/db/myki.csv`

**Comment by WNemencha** [comment]
Done ;)

**Comment by arturgoms** [comment]
@WNemencha The tests are failing because you remove the group key from the manager  but not from the tests. 
To fix that you should add 
```  
without:
    - group
 ```

under the MyKi section in the [tests.py](https://github.com/roddhjav/pass-import/blob/master/tests/tests.yml) file.

**Comment by WNemencha** [comment]
Done, 🤞

**Comment by WNemencha** [comment]
No problemo, your tool was such a delight to have in this shitty situation, shame on JumpCloud ;)

**Pull request merged**
