### PR TITLE
Raise an exception upon invalid LastPass CSV data

### PR DESCRIPTION
**Pull request by boltronics**
Please see the comment I have added to the code, explaining why I did what I did.

From a LastPass CSV export of well over 2000 passwords, I discovered six of the entries were corrupt in the way described. Having the data with the issue shown in the exception allowed me to quickly identify the problematic entries, confirm they were invalid, and manually delete them (while making note of them for manually exporting afterwards).

Feel free to change the exception to something more appropriate (or otherwise let me know if you want me to change it somehow). Thanks!

### CODE REVIEW

**Comment by roddhjav** [comment]
Hi, thanks a lot for this PR.

Can you use the  `FormatError` exception  from `pass_import.errors` as `pass_import.ManagerError` is more an internal error.

**Comment by boltronics** [comment]
No worries. I figured there might be a better one - thanks for pointing that out. Will fix this momentarily.

**Comment by boltronics** [comment]
I think that should now be sorted, provided it also looks good to you. Thanks!

**Comment by roddhjav** [comment]
Merged. Thanks again for the bug catch and the nice fix.

**Pull request merged**
