### PR TITLE
add gopass support

### PR DESCRIPTION
**Pull request by thomas-mc-work**
This is probably the most simple solution for a gopass provider. It inherits from the existing `pass` manager while adjusting only the class parameters.

### CODE REVIEW

**Comment by thomas-mc-work** [comment]
Somehow this seems to have broken the tests. But I cannot explain why. Can you help, @roddhjav ?

**Comment by roddhjav** [comment]
Hey, thank for the PR. The tests failed because the way you implemented the class it expects the gopass command line to be installed. (witch it is not in the test env). I will have a deeper look at it soon.

**Comment by pradyumnac** [comment]
I am not sure about the status of this PR. I see chrome as listed export option in docs

However, I am trying to run 
```bash
pimport gopass chrome xdg.csv
```
It gives 
image

Any ideas? My gopass is set up and synced

**Comment by roddhjav** [comment]
As per https://github.com/roddhjav/pass-import#basic-use, you need to use the `--out` option to tell `pimport` where is your gopass repository.

**Pull request merged**
