### PR TITLE
Add enpass2pass

### PR DESCRIPTION
**Pull request by wfleming**
Hi @roddhjav,

I recently wrote [a script](https://github.com/wfleming/enpass2pass) to migrate my [Enpass](https;//enpass.io) database into `pass`. Since your plugin make it so easy for new `pass` users to move their old databases over, I figured it would be helpful to other Enpass users if it could be included in your plugin. Hopefully this looks OK to you.

Thanks!

### CODE REVIEW

**Comment by roddhjav** [comment]
Thank a lot for this PR. This new importer script could be useful for some new users, I will certainly merge it into master soon. Just allow a bit of time so that I can review and test it.

**Comment by wfleming** [comment]
No rush! Let me know if you have any questions about the code.

> and test it.

I read through `tests/runtests` a bit to see if I could help by adding a test input, but I got the impression it was a testing harness you run against local source databases that aren't checked in here. Not sure if I missed something, but if providing sample input would be helpful I can do that.

**Comment by roddhjav** [comment]
I'm actually in the process of creating a real test system (using [sharness](https://github.com/chriscool/sharness) as the test suite) and real password database as input for all the password manager pass-tomb support. As you can image it is quite long, this is why the tests directory is quite useless right now.

Sample would be indeed a lot helpful ;)

**Comment by wfleming** [comment]
Sorry this took we a while: life intervened, and I needed to take the time to generate some fake logins with real-looking data for the sample. I've uploaded a sample CSV as a gist: https://gist.github.com/wfleming/f528582a5e5b80b6bcb78b917c81e94e

**Comment by roddhjav** [comment]
Sorry for the delay. Everything looks good to me, I'm going to merge it. 
Once I'll have the time, I'll add a proper test suite for it.

Thank again for this PR.

**Pull request merged**
